### ISSUE TITLE
Add "/" as acceptable URL character

### ISSUE THREAD

**Issue by burkeholland** [the-urlist/backend-csharp#5]
Right now we disallow the "/" character. Having one would make it possible to "namespace" links and also vastly increases the available permutations and decrease collisions.

This would be paticularly helpful for people who have recurring themes like...

theurlist.com/twitch/some-links
theurlist.com/build/some-session
theurlist.com/username/all-a-users-links

**Comment by cecilphillip** [comment]
@burkeholland should we allow users to request to reserve namespaces? That could start getting complicated I suppose
